### ISSUE TITLE
Auto keep alive not working

### ISSUE THREAD

**Issue by ctron** [vert-x3/vertx-mqtt#123] opened 2019-03-20 08:39 UTC
The auto keep alive seems not to be working. Checking the source I assume this is due to the following way it is implemented:

~~~java
pipeline.addBefore("handler", "idle",new IdleStateHandler(0, this.options.getKeepAliveTimeSeconds(), 0));
~~~

This will register an idle detector which only listens for write events. However, opening a connection and only pushing QoS messages will not trigger a response from the server,
so the client does never receive anything from the server.

The client should send a PINGREQ when the **reader** gets idle. Which shouldn't happen
when you send QoS 1 or 2 messages and the server sends responses. However if it does,
then sending a PINGREQ would be the appropriate action.

If the server doesn't response then, it should be considered dead.

**Comment by vietj** [comment] 2019-03-20 08:43
@ctron so this is mainly an mqtt-client concern right ?

**Comment by ctron** [comment] 2019-03-20 08:46
> @ctron so this is mainly an mqtt-client concern right ?

Yes, this is an issue in the MQTT client.

**Comment by vietj** [comment] 2019-03-20 08:49
so basically we should set a timer on the client to periodically send PING commands to the server and that's it right ?

**Comment by ctron** [comment] 2019-03-20 14:57
> so basically we should set a timer on the client to periodically send PING commands to the server and that's it right ?

Well you don't need a timer, a simple "reader idle" condition should work, swapping that with the current "writer idle".

**Comment by vietj** [comment] 2019-03-20 20:16
what do you mean ?

**Comment by ctron** [comment] 2019-03-21 07:41
Swapping the current reader idle condition with writer idle …

**Comment by vietj** [comment] 2019-03-21 07:50
ahhh... that makes sense lol :-) sorry

**Comment by vietj** [comment] 2019-03-21 07:50
how can we best make a reproducer test for this ?

**Comment by ctron** [comment] 2019-03-21 07:53
> how can we best make a reproducer test for this ?

I am not that familiar with testing in vertx. However the test should be:

Common start

* Create a connection, with an auto-handshake period of X seconds
* Start sending QoS 0 messages to the server, every 1 second
* After X seconds, the client should automatically send a PINGREQ

Variant A:

* The server does not respond
* The connection must be closed after X mutliplied by 1.5 seconds (MQTT spec)

Variant B:

* The server responds with a PINGRESP
* After X more seconds, the connection must still be open

**Comment by vietj** [comment] 2019-03-21 07:55
that's what I actually asked for :-) thanks.

**Comment by ctron** [comment] 2019-03-21 07:56
> that's what I actually asked for :-) thanks.

Cool :smile: … thanks for looking into this!

**Comment by vietj** [comment] 2019-03-25 08:40
I'm working on it @ctron , I can't see where the `1.5` multiplier is specified in the spec, all I can read is _If a Client does not receive a PINGRESP Packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server._

**Comment by ctron** [comment] 2019-03-25 08:51
MQTT Spec:

> If the Keep Alive value is non-zero and the Server does not receive a Control Packet from the Client within one and a half times the Keep Alive time period, it MUST disconnect the Network Connection to the Client as if the network had failed [MQTT-3.1.2-24].

**Comment by vietj** [comment] 2019-03-25 10:00
@ctron it seems this statement applies to the server and not the client

**Comment by vietj** [comment] 2019-03-25 12:15
@ctron please see https://github.com/vert-x3/vertx-mqtt/issues/124 which provides a better handling of client ping expiration

**Comment by konradmichael** [comment] 2019-03-25 13:16
You are aware, that I made a simmilar issue? Including a PR?
Issue: https://github.com/vert-x3/vertx-mqtt/issues/117
PR: https://github.com/vert-x3/vertx-mqtt/pull/118

I have no Idea why you closed it.

**Comment by vietj** [comment] 2019-03-25 14:19
@konradmichael yes I remember now, I tried also to use the READER idle state but it did not work in all cases. Basically writing to the channel a message defeats the idle state and the client does not get properly timeout, so I had to use Vertx timers instead.

**Comment by vietj** [comment] 2019-03-25 14:20
also the 1.5 factor does not apply to the client but to the server instead. That's why there is a `keepAliveTimeout` value to specify how long on the client side a disconnect should happen when a ping response is not received from the server

**Comment by vietj** [comment] 2019-03-25 14:21
you can help to review the PR @konradmichael

**Comment by ctron** [comment] 2019-03-25 14:38
> @ctron it seems this statement applies to the server and not the client

Maybe you should have a look at the whole section, that might explain it:

> If a Client does not receive a PINGRESP Packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server.

**Comment by vietj** [comment] 2019-03-25 15:06
it says a reasonable time.

the server has the 1.5 factor requirement

as far as I can read

**Comment by ctron** [comment] 2019-03-25 16:49
So what would be the definition of "reasonable"?

**Comment by vietj** [comment] 2019-03-25 17:13
there is a new property in the `MqttClientOptions` called `keepAliveTimeout` of 10 seconds by default in the PR

**Comment by ctron** [comment] 2019-03-26 07:52
> there is a new property in the MqttClientOptions called keepAliveTimeout of 10 seconds by default in the PR

With the meaning of "10 seconds after the PINGREQ was sent, a response is overdue"? … I guess that would work.

**Comment by ctron** [comment] 2019-03-26 08:00
I just had a look at the PR, and I think this really overcomplicates things.

When you send out a PINGREQ, you expected a PINGRESP to come back. In most cases you don't really care about getting back and PINGRESP or "something else" from the server. The PINGREQ is just a trigger to make the server send you something. This way you can reset the "idle reader" condition.

My proposal would be to:
* set an IDLE reader timeout to "keepalive"
* when the IDLE reader condition triggers, send a PINGREQ and set the IDLE reader timeout to "keepalive timeout"

Option A:

* on the next packet received reset the IDLE reader timeout back to "keepalive"

Option B:

* when the IDLE reader is triggered again, close the connection

**Comment by vietj** [comment] 2019-03-26 09:15
@ctron I followed your advice and simplified the code, can you check ?

**Comment by ctron** [comment] 2019-03-26 09:32
I am sorry, but I don't understand what the intention of the last change is.

To my understanding now what happens is that the PINGREQ is simple sent periodically, but no one ever checks if the reader is IDLE now, or closes the connection?!

**Comment by konradmichael** [comment] 2019-03-26 09:38
> I am sorry, but I don't understand what the intention of the last change is.

Same to me here.
Using the reader idle state seems to be the best solution.

**Comment by vietj** [comment] 2019-03-26 09:54
@ctron yes it does, the connection is closed in the pingCheck methods, there are tests for this. The intention is to simplify

**Comment by vietj** [comment] 2019-03-26 09:55
@konradmichael I will try with reader idle state and let you know if that's feasible. I think I tried already and it failed.

**Comment by vietj** [comment] 2019-03-26 09:57
@ctron the `pingCheck()` method is a state machine that implements the behavior you described in your comment:

```
  private void pingCheck() {
    if (this.timerID == -1) {
      this.pingSent = false;
      this.timerID = this.ctx.owner().setTimer(options.getKeepAliveTimeSeconds() * 1000, id -> pingCheck());
    } else if (pingSent) {
      this.pingSent = false;
      this.timerID = -1;
      this.connection.close();
    } else {
      this.pingSent = true;
      this.timerID = this.ctx.owner().setTimer(pingTimeout, id -> pingCheck());
      this.ping();
    }
  }
```

**Comment by vietj** [comment] 2019-03-26 09:59
state goes from

timerID == -1 : no ping has been scheduled to be sent, so schedule a ping
timerID != -1 && !pingSent : schedule a ping
timerID != -1 && pingSent : close the connection

when a ping response is received : reset state and make progress in automaton again.

**Comment by vietj** [comment] 2019-03-26 10:10
@konradmichael I think that one issue of using `IdleStateHandler` is that it only takes in account the reader event. So when we send a ping request to the server, the handler will not reset the idle read timer when the ping request traverses the pipeline. In general `IdleStateHandler` is great when you want to check idle-ness independently of the messages.

**Comment by konradmichael** [comment] 2019-03-26 10:35
I think we both understand your state machine.
But you are still periodically sending the ping request. And this is a "bad" behavior as it produces unnecessary traffic.

And all I can say to the Idle-Handler is, that it was working in my test-setup. If i find the time I can reverify it.

**Comment by ppatierno** [comment] 2019-03-26 17:06
Finally I had the time to take a quick look at the PR.
First of all, I think that we are creating an ambiguity for who knows the MQTT world and now he sees `keepAliveTimeSeconds` and `keepAliveTimeout`. The second thing, is that the code seems to be over complicated. I would love having the result from @konradmichael if the idle just works to simplify.
As far as I understand from the code, the `pingCheck` related timer just starts on connect even if there is no PINGREQ sent. At some point it starts to send PINGREQ. Of course, it's possible that the MQTT client is so active that there is never need for sending a PINGREQ because the connection has always traffic so the timer is sending not usefull PINGREQ, or am I missing something?

**Comment by vietj** [comment] 2019-03-26 18:00
As I said, I believe it is not possible to implement this with @konradmichael solution for the reason I explained. Of course I might be wrong and I would be glad, so I believe that @konradmichael can provide a new PR. His original PR did not have any tests, mine has and I believe they are correct. @konradmichael is welcome to reuse the tests I wrote.

In addition @konradmichael was wrong on the `1.5` factor applied to the client side, whereas the spec clearly say that this is a server concern and he should have introduced a configurable timeout on the client.

I named it `keepAliveTimeout` because `MqttClientOptions` extends `NetClientOptions` which has `idleTimeout` so I believe actually that
   - it is correct to name it `keepAliveTimeout`
   - `keepAliveTimeSeconds` is actually an incorrect name and instead if should be `keepAlivePeriod` as we are specifying a period, so `keepAliveTimeSeconds` should be deprecated in favor of the more correct `keepAlivePeriod` instead

So for now I believe we are going to leave this out for 3.7.0 (that shall be released this week), until we figure out the issues mentioned above.

**Comment by ppatierno** [comment] 2019-03-26 19:45
Did you test what I mention about having PINGREQ sent even when the channel is busy writing?
It seems to me that even when the MQTT client is sending data (i.e. PUBLISH messages, or PUBACK as ack for received packets, ...) the timer always sends PINGREQ which is not necessary.
I would agree on the `KeepAliveTimeSeconds` name but I would use `keepAliveInterval` as mentioned in the spec and heavily used in the Eclipse Paho library which is the reference for MQTT implementations. Btw even in this case I would leave it for a different PR.

**Comment by vietj** [comment] 2019-03-26 19:57
> On 26 Mar 2019, at 20:45, Paolo Patierno <notifications@github.com> wrote:
> 
> Did you test what I mention about having PINGREQ sent even when the channel is busy writing?
> 

can you explicit what a test case would be ? that leaves any ambiguity

> It seems to me that even when the MQTT client is sending data (i.e. PUBLISH messages, or PUBACK as ack for received packets, ...) the timer always sends PINGREQ which is not necessary.
> I would agree on the KeepAliveTimeSeconds name but I would use keepAliveInterval as mentioned in the spec and heavily used in the Eclipse Paho library which is the reference for MQTT implementations. Btw even in this case I would leave it for a different PR.
> 
> 

Interval is actually equivalent to Period and better if the spec use this word so I believe we should go for deprecating keepAliveTimeSeconds in favour of keepAliveInterval, can you open an issue for this ?

**Comment by ppatierno** [comment] 2019-03-28 05:51
I have just created issue #126

**Comment by konradmichael** [comment] 2019-03-28 13:52
New Pull request: #129

**Closed** 2020-10-07 16:58 UTC
Labels: bug, help wanted

**Comment by AlmostRuio** [comment] 2020-12-01 11:01
@vietj  @konradmichael  Hello, any chance that this fix will be applied to 4.0.0? In our project we are actually using 4.0.0.CR1 and we have this problem. Thank you and have a nice day!

**Comment by vietj** [comment] 2020-12-01 11:56
it is supposedly applied https://github.com/vert-x3/vertx-mqtt/pull/173

do you have a reproducer ?

**Comment by AlmostRuio** [comment] 2020-12-01 14:02
@vietj i hope i didn't forgot something in my code, if is the case i'm really sorry.
The server is moquitto, running in a local docker image.
vertx 4.0.0.RC2

```

    @Override
    public void start() {
        String brokerHost = getenv("BROKER_HOST");
        String portFromEnv = getenv("BROKER_PORT");
        int brokerPort = portFromEnv != null ? parseInt(portFromEnv) : BROKER_PORT;

        MqttClientOptions options = new MqttClientOptions();
        options.setAutoKeepAlive(true);
        client = MqttClient.create(vertx, options);

        Handler<AsyncResult<MqttConnAckMessage>> connectionHandler = ar -> {
            if (ar.succeeded()) {
                LOGGER.info("connected to {}:{}", brokerHost, brokerPort);
            } else {
                LOGGER.error("failed to connect to MQTT broker", ar.cause());
            }
        };
        client.connect(brokerPort, brokerHost, connectionHandler);

        client.closeHandler(handler -> {
            LOGGER.warn("connection to broker closed, reconnect");

            // the handling of the ping-req for connection "keepAlive" does not work correctly, if there
            // is no publishing (only consuming messages disables the ping's in the implementation of
            // io.vertx.mqtt.impl.MqttClientImpl#initChannel since version 3.9.4 due to the changes described
            // in this issue: https://github.com/vert-x3/vertx-mqtt/issues/123)
            // workaround for now is to reconnect if the MQTT server closes the connection
            client.connect(brokerPort, brokerHost, connectionHandler);
        });

        scheduleNextUpdate();

        LOGGER.info("{} ready!", SimulatorExternalData.class.getName());
    }
```

**Comment by vietj** [comment] 2020-12-01 15:33
can you open a new issue with the reproducer ? if you can provide a project it is better.

**Comment by AlmostRuio** [comment] 2020-12-02 07:08
@vietj done
https://github.com/vert-x3/vertx-mqtt/issues/183

**Comment by vietj** [comment] 2020-12-02 07:20
thanks @AlmostRuio

**Comment by alamothe** [comment] 2022-03-13 22:00
@vietj It looks like the fix is not on master at all. We are using Vert.x 4.1.5 and it does not have the fix. 

Any idea why?

**Comment by alamothe** [comment] 2022-03-13 22:07
This commit: https://github.com/vert-x3/vertx-mqtt/commit/1bae9fec06314921cbb28a8a9d1411c0565e687b

Changed `ALL_IDLE` to `WRITER_IDLE`.

We are still getting disconnected every 30 seconds.
